import tseslint from 'typescript-eslint'
import { enginePurityRules } from './packages/engine/eslint.config.js'

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/coverage/**',
      '**/node_modules/**',
      // Generated by Next on every build; not ours to style.
      'apps/web/next-env.d.ts',
      // Built by the bridge; generated, minified, not ours to style.
      'vyakarana/static/**',
      // The ADR-004 spike's gitignored engine bundle, when present locally.
      'spikes/**/*.js',
      // A Claude Design canvas export the repo carries as an artifact.
      'Tape-n-Trace UI Overhaul/**',
    ],
  },

  ...tseslint.configs.recommended,

  {
    rules: {
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],
      eqeqeq: ['error', 'always'],
      'no-console': 'error',
    },
  },

  // The engine import ban. architecture.md §2.1 — enforced here, failing CI.
  {
    files: ['packages/engine/**/*.ts'],
    rules: enginePurityRules,
  },

  // Tests exercise the invariants the engine forbids callers from relying on,
  // and need a clock and an RNG seed of their own.
  {
    files: ['packages/engine/test/**/*.ts'],
    rules: {
      'no-restricted-properties': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // Renderers are pure: they receive a trace and draw it, and never call the
  // engine (§2.3, §10.1). Types are the one exception — a type-only import
  // erases at build time, so it creates no runtime dependency and no bundle
  // weight. That distinction is what lets the notebook bridge reuse these
  // components without shipping the engine alongside them.
  {
    files: ['packages/ui/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@tape-n-trace/engine',
              message:
                'Renderers draw a trace, they never compute one. Import the types only, and let the controller call the engine.',
              allowTypeImports: true,
            },
          ],
          patterns: [
            {
              group: ['@tape-n-trace/engine/*'],
              message:
                'Renderers draw a trace, they never compute one. Import the types only, and let the controller call the engine.',
              allowTypeImports: true,
            },
          ],
        },
      ],
      // No component both computes and renders, none over ~300 lines (§2.4).
      'max-lines': ['error', { max: 300, skipBlankLines: true, skipComments: true }],
    },
  },

  // Renderer tests are not renderers. They call the engine on purpose, to
  // produce the real traces the components are then measured against — a
  // snapshot test against a hand-written fake trace would pass forever while the
  // renderer drifted away from what the engine actually emits.
  {
    files: ['packages/ui/test/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-restricted-imports': 'off',
      'max-lines': 'off',
    },
  },

  // The bridge draws in a notebook what the web app draws in the browser,
  // from the same renderers. It may import packages/ui and packages/engine and
  // nothing from apps/web (phases-vyakarana.md V1) — the build's metafile
  // check enforces the same boundary on the emitted bundle.
  {
    files: ['bridge/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/apps/web/**', '**/apps/**'],
              message: 'The bridge imports packages/ui and packages/engine only (phases-vyakarana.md V1).',
            },
          ],
        },
      ],
      'max-lines': ['error', { max: 300, skipBlankLines: true, skipComments: true }],
    },
  },

  // The same size rule applies to the app's own components. A controller that
  // grows past 300 lines has stopped being a controller and started being a
  // controller plus a renderer plus some docs (§2.4).
  {
    files: ['apps/web/**/*.tsx'],
    rules: {
      'max-lines': ['error', { max: 300, skipBlankLines: true, skipComments: true }],
    },
  },
)
