/**
 * Module 2 exercises — regular expressions and regular languages, from the bank.
 *
 * construct-re answers are graded by converting both expressions to minimal DFAs
 * and comparing languages, so any equivalent expression passes — `(a+b)*` and
 * `(a*b*)*` are both right, exactly as a marker would allow.
 */

import type { Exercise } from '../../lib/exercises'

export const MODULE2: Exercise[] = [
  {
    id: 'm2-re-even-binary',
    topic: 'regex.basics',
    prompt: 'Write a regular expression for binary numerals that are multiples of 2.',
    kind: 'construct-re',
    reference: { kind: 'regex', source: '(0+1)*0', alphabet: ['0', '1'] },
    grader: 'language-equivalence',
    hints: ['A binary numeral is even exactly when it ends in 0.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    part: 'a',
    source: 'Question Bank #19(i)',
  },
  {
    id: 'm2-re-consecutive-a',
    topic: 'regex.basics',
    prompt: "Write a regular expression for strings of a's and b's containing consecutive a's.",
    kind: 'construct-re',
    reference: { kind: 'regex', source: '(a+b)*aa(a+b)*', alphabet: ['a', 'b'] },
    grader: 'language-equivalence',
    hints: ['Anything, then aa, then anything.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    part: 'b',
    source: 'Question Bank #19(iii)',
  },
  {
    id: 'm2-re-odd-length',
    topic: 'regex.basics',
    prompt: "Write a regular expression for strings of a's and b's having odd length.",
    kind: 'construct-re',
    reference: { kind: 'regex', source: '(a+b)((a+b)(a+b))*', alphabet: ['a', 'b'] },
    grader: 'language-equivalence',
    hints: ['One symbol, then any number of pairs.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    part: 'b',
    source: 'Question Bank #19(iv)',
  },
  {
    id: 'm2-re-third-fourth-right',
    topic: 'regex.basics',
    prompt: 'Write a regular expression for strings of a’s and b’s whose third symbol from the right is a and fourth from the right is b.',
    kind: 'construct-re',
    reference: { kind: 'regex', source: '(a+b)*ba(a+b)(a+b)', alphabet: ['a', 'b'] },
    grader: 'language-equivalence',
    hints: [
      'Fix the last four symbols: b, then a, then any two.',
      'Anything at all may come before them.',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    part: 'c',
    source: 'Question Bank #19(v)',
  },
  {
    id: 'm2-nfa-aa-star',
    topic: 'regex.to-nfa',
    prompt: 'Design an NDFSM accepting the language of aa*(a+b).',
    kind: 'construct-nfa',
    reference: { kind: 'regex', source: 'aa*(a+b)', alphabet: ['a', 'b'] },
    grader: 'language-equivalence',
    hints: ['One or more a’s, then exactly one more symbol.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    part: 'a',
    source: 'Question Bank #20(i)',
  },
  {
    id: 'm2-nfa-ends-00-11',
    topic: 'regex.to-nfa',
    prompt: 'Design an NDFSM accepting the language of (0+1)*(00+11).',
    kind: 'construct-nfa',
    reference: { kind: 'regex', source: '(0+1)*(00+11)', alphabet: ['0', '1'] },
    grader: 'language-equivalence',
    hints: ['Guess where the final doubled pair begins — that guess is the nondeterminism.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    part: 'b',
    source: 'Question Bank #20(ii)',
  },
  {
    id: 'm2-enfa-aabb-b',
    topic: 'regex.to-nfa',
    prompt: 'Obtain an ε-NFA for the regular expression (aa)*(bb)*b.',
    kind: 'construct-nfa',
    reference: { kind: 'regex', source: '(aa)*(bb)*b', alphabet: ['a', 'b'] },
    grader: 'language-equivalence',
    hints: [
      'Thompson’s construction gives it mechanically — one fragment per operator.',
      'Or reason directly: pairs of a’s, then pairs of b’s, then a single b.',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    part: 'a',
    source: 'Question Bank #21(i)',
  },
  {
    id: 'm2-enfa-contains-00-11',
    topic: 'regex.to-nfa',
    prompt: 'Obtain an ε-NFA for the regular expression (0+1)*(00+11)(0+1)*.',
    kind: 'construct-nfa',
    reference: { kind: 'regex', source: '(0+1)*(00+11)(0+1)*', alphabet: ['0', '1'] },
    grader: 'language-equivalence',
    hints: ['The language is simply: contains a doubled symbol somewhere.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    part: 'b',
    source: 'Question Bank #21(ii)',
  },
  {
    id: 'm2-re-mod3-length',
    topic: 'regex.basics',
    prompt: 'Obtain a regular expression for L = {w ∈ (a+b)* : |w| mod 3 = 0}.',
    kind: 'construct-re',
    reference: { kind: 'regex', source: '((a+b)(a+b)(a+b))*', alphabet: ['a', 'b'] },
    grader: 'language-equivalence',
    hints: ['Group the string into blocks of three symbols.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    part: 'c',
    source: 'Question Bank #18(iii)',
  },
  {
    id: 'm2-closure-proofs',
    topic: 'regular.closure',
    prompt: 'Show that the regular languages are closed under (a) union, (b) concatenation, (c) star closure and (d) intersection.',
    kind: 'explain',
    reference: { kind: 'none' },
    grader: 'manual',
    hints: [
      'Union, concatenation and star fall straight out of regular expressions.',
      'Intersection needs the product construction — build it in the closure lab and describe what you see.',
      'The lab shows union, intersection and difference are one walk with three accepting conditions.',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    source: 'Question Bank #25',
  },
  {
    id: 'm2-pump-anbn',
    topic: 'regular.pumping',
    prompt: 'Prove that L = {aⁿbⁿ | n ≥ 0} is not regular.',
    kind: 'pumping',
    reference: { kind: 'none' },
    grader: 'manual',
    hints: [
      'Pick w = aⁿbⁿ where n is the pumping length; |xy| ≤ n forces y inside the a-block.',
      'Pumping y changes the number of a’s but not b’s.',
      'The pumping game (P1.2) will let you play this against an adversary.',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    source: 'Question Bank #27',
  },
  {
    id: 'm2-pump-0n1m',
    topic: 'regular.pumping',
    prompt: 'Prove that L = {0ⁿ1ᵐ | n ≤ m} is not regular.',
    kind: 'pumping',
    reference: { kind: 'none' },
    grader: 'manual',
    hints: [
      'Choose w = 0ⁿ1ⁿ. The decomposition traps y among the 0s.',
      'Pump *up*: more 0s than 1s breaks n ≤ m.',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    source: 'Question Bank #28',
  },
  {
    id: 'm2-pump-prime',
    topic: 'regular.pumping',
    prompt: 'Prove that L = {0ⁿ | n is prime} is not regular.',
    kind: 'pumping',
    reference: { kind: 'none' },
    grader: 'manual',
    hints: [
      'Pick a prime p ≥ n and pump i = p + 1 times: the length becomes p + p·|y| = p(1 + |y|), composite.',
      'The arithmetic is the whole proof — the automaton machinery just sets it up.',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    source: 'Question Bank #29',
  },
  {
    id: 'm2-pump-wwr',
    topic: 'regular.pumping',
    prompt: 'State and prove the pumping theorem for regular languages, and prove that L = {wwᴿ | w ∈ {a,b}*} is not regular.',
    kind: 'pumping',
    reference: { kind: 'none' },
    grader: 'manual',
    hints: [
      'The statement has three quantifier alternations — get them in the right order first.',
      'For wwᴿ, pick aⁿbbaⁿ and pump inside the first a-block; the palindrome breaks.',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO2',
    source: 'Question Bank #26',
  },
]
