/**
 * Modules 3–5 — grammars, PDAs, CFL properties and Turing machines.
 *
 * These are `grader: 'manual'` and honestly so: the CFG, PDA and TM engines
 * arrive in P1.3–P1.6, and CL2 prose questions have no automatable grader at
 * all. Faking a check would be worse than saying "marked by hand". They are in
 * the bank now so the practice index spans every module, the CIE-II filter has
 * content, and the prompts carry their real marks and tags from day one.
 */

import type { Exercise } from '../../lib/exercises'

const manual = (
  exercise: Omit<Exercise, 'reference' | 'grader' | 'kind'> & { kind?: Exercise['kind'] },
): Exercise => ({
  ...exercise,
  kind: exercise.kind ?? 'explain',
  reference: { kind: 'none' },
  grader: 'manual',
})

export const THEORY: Exercise[] = [
  // ---- Module 3 — CFGs and PDAs -------------------------------------------
  manual({
    id: 'm3-cfg-define',
    topic: 'cfg.basics',
    prompt: 'What is a context-free grammar? Explain a CFG with an example.',
    hints: ['Give the 4-tuple (V, T, P, S) and one small grammar, e.g. S → aSb | ε, with a derivation.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO3',
    source: 'Question Bank #31',
  }),
  manual({
    id: 'm3-cfg-mod3',
    topic: 'cfg.basics',
    prompt: 'Obtain a CFG generating strings of a’s and b’s where L = {w : |w| mod 3 = 0}.',
    hints: ['The language is regular, so a right-linear grammar mirroring the 3-state DFA works.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO3',
    source: 'Question Bank #32',
  }),
  manual({
    id: 'm3-lmd-rmd',
    topic: 'cfg.derivations',
    prompt: 'For E → E+E | E*E | (E) | id, construct the LMD, RMD and parse tree for (id+id*id).',
    hints: [
      'Leftmost: always expand the leftmost variable; rightmost: the rightmost.',
      'The two derivations give the same tree when the parse is unambiguous — is this one?',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO3',
    part: 'a',
    source: 'Question Bank #35',
  }),
  manual({
    id: 'm3-ambiguous-asb',
    topic: 'cfg.ambiguity',
    prompt: 'Check whether the grammar S → aSb | SS | ε is ambiguous.',
    hints: ['Find one string with two different leftmost derivations — think about how SS can split.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO3',
    part: 'b',
    source: 'Question Bank #36',
  }),
  manual({
    id: 'm3-ambiguous-expr',
    topic: 'cfg.ambiguity',
    prompt: 'For G with E → E+E | E*E | (E) | id over the input a + b * c, prove the grammar is ambiguous.',
    hints: ['Two parse trees: one grouping (a+b)*c, one grouping a+(b*c).'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO3',
    part: 'b',
    source: 'Question Bank #37',
  }),
  manual({
    id: 'm3-left-recursion',
    topic: 'cfg.left-recursion',
    prompt: 'Define left recursion. Eliminate left recursion from: E → E+T | T,  T → T*F | F,  F → (E) | id.',
    hints: [
      'A → Aα | β becomes A → βA′, A′ → αA′ | ε.',
      'This is the exam’s own expression grammar — the P1.3 stepper will animate it.',
    ],
    marks: 6,
    bloom: 'CL4',
    co: 'CO3',
    part: 'a',
    source: 'Question Bank #42',
  }),
  manual({
    id: 'm3-pda-anbn',
    topic: 'pda.basics',
    prompt: 'Define a PDA. Design a PDA accepting L = {aⁿbⁿ : n ≥ 0}, draw its transition diagram, and show the IDs for aaabbb.',
    hints: [
      'Push an X per a; pop an X per b; accept on empty stack or final state.',
      'The ID sequence (q, w, γ) is what the exam marks — write every configuration.',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO3',
    part: 'a',
    source: 'Question Bank #55',
  }),
  manual({
    id: 'm3-pda-wcwr',
    topic: 'pda.basics',
    prompt: 'Construct a PDA accepting L = {wcwᴿ : w ∈ {a,b}*}, and show its moves on "aabcbaa".',
    hints: ['Push before the c, match-and-pop after it — the c tells you when to turn around.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO3',
    part: 'b',
    source: 'Question Bank #54',
  }),
  manual({
    id: 'm3-cfg-to-pda',
    topic: 'pda.cfg',
    prompt: 'Construct a PDA for the CFG S → 0BB, B → 0S | 1S | 0, and test whether 010000 is accepted.',
    hints: ['The standard construction: expand variables on the stack, match terminals against input.'],
    marks: 6,
    bloom: 'CL4',
    co: 'CO3',
    part: 'c',
    source: 'Question Bank #50',
  }),
  manual({
    id: 'm3-pda-cfg-equiv',
    topic: 'pda.cfg',
    prompt: 'Explain the equivalence of PDAs and CFGs with a proper example.',
    hints: ['One direction is the grammar-to-PDA construction; state the other and sketch why it holds.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO3',
    source: 'Question Bank #57',
  }),

  // ---- Module 4 — CFL properties ------------------------------------------
  manual({
    id: 'm4-cnf-1',
    topic: 'cfg.cnf',
    prompt: 'Eliminate ε-, unit and useless productions from S → aA | aBB, A → aAA | ε, B → bB | bbC, C → B, and convert to CNF.',
    hints: [
      'Order matters: nullable symbols first, then unit pairs, then useless symbols, then CNF.',
      'Getting the order wrong leaves a residual symbol — the P1.5 pipeline will show it.',
    ],
    marks: 6,
    bloom: 'CL4',
    co: 'CO4',
    part: 'a',
    source: 'Question Bank #63',
  }),
  manual({
    id: 'm4-cnf-2',
    topic: 'cfg.cnf',
    prompt: 'Convert to CNF: S → aACa, A → AB | a, B → BC | c, C → CCc | ε.',
    hints: ['Isolate terminals into their own variables first, then binarise long bodies.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO4',
    part: 'b',
    source: 'Question Bank #65',
  }),
  manual({
    id: 'm4-cfl-pump-0n1n2n',
    topic: 'cfl.pumping',
    prompt: 'Determine whether L = {0ⁿ1ⁿ2ⁿ | n ≥ 1} is context-free.',
    hints: [
      'The CFL pumping lemma splits w = uvxyz with |vxy| ≤ n — the window cannot cover all three blocks.',
      'Whichever two blocks pump, the third is left behind.',
    ],
    marks: 5,
    bloom: 'CL4',
    co: 'CO4',
    part: 'a',
    source: 'Question Bank #59',
  }),
  manual({
    id: 'm4-cfl-pump-ww',
    topic: 'cfl.pumping',
    prompt: 'Show that L = {ww | w ∈ {0,1}*} is not context-free.',
    hints: ['Pick w = 0ⁿ1ⁿ0ⁿ1ⁿ and case-split on where the |vxy| ≤ n window can sit.'],
    marks: 6,
    bloom: 'CL4',
    co: 'CO4',
    part: 'b',
    source: 'Question Bank #60',
  }),
  manual({
    id: 'm4-cfl-closure',
    topic: 'cfl.closure',
    prompt: 'Show that CFLs are closed under union, concatenation, star, homomorphism and reversal.',
    hints: ['Each is one grammar construction: new start productions for union, S → S₁S₂ for concatenation…'],
    marks: 6,
    bloom: 'CL4',
    co: 'CO4',
    part: 'a',
    source: 'Question Bank #68',
  }),
  manual({
    id: 'm4-cfl-non-closure',
    topic: 'cfl.closure',
    prompt: 'Prove that CFLs are not closed under intersection or complementation.',
    hints: [
      '{aⁿbⁿcᵐ} ∩ {aᵐbⁿcⁿ} = {aⁿbⁿcⁿ}, which the pumping lemma kills.',
      'Complement then falls by De Morgan — closure under it would give closure under intersection.',
    ],
    marks: 6,
    bloom: 'CL4',
    co: 'CO4',
    part: 'b',
    source: 'Question Bank #67',
  }),
  manual({
    id: 'm4-cfl-intersect-regular',
    topic: 'cfl.closure',
    prompt: 'Prove that if L is a CFL and R is a regular language, then L ∩ R is a CFL.',
    hints: ['Run a PDA and a DFA in product — the stack belongs to the PDA alone.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO4',
    part: 'c',
    source: 'Question Bank #64',
  }),

  // ---- Module 5 — Turing machines and undecidability ----------------------
  manual({
    id: 'm5-tm-define',
    topic: 'tm.basics',
    prompt: 'Define a Turing machine. With a neat diagram, explain the working of a basic Turing machine.',
    hints: ['The 7-tuple, the tape, the head, and one worked move — that is the whole answer.'],
    marks: 6,
    bloom: 'CL4',
    co: 'CO5',
    source: 'Question Bank #72',
  }),
  manual({
    id: 'm5-tm-0n1n',
    topic: 'tm.basics',
    prompt: 'Obtain a TM accepting L = {0ⁿ1ⁿ | n ≥ 1}; draw the transition diagram and show the moves on 000111.',
    hints: [
      'Mark a 0, run right to mark a matching 1, run back; repeat.',
      'The ID log — every configuration in order — is what the exam marks.',
    ],
    marks: 8,
    bloom: 'CL4',
    co: 'CO5',
    part: 'a',
    source: 'Question Bank #74',
  }),
  manual({
    id: 'm5-tm-ends-011',
    topic: 'tm.basics',
    prompt: 'Obtain a TM accepting strings of 0’s and 1’s ending with 011.',
    hints: ['A TM for a regular language may simply sweep right and check the suffix at the blank.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO5',
    part: 'b',
    source: 'Question Bank #75',
  }),
  manual({
    id: 'm5-tm-palindrome',
    topic: 'tm.basics',
    prompt: 'Design a TM accepting all palindromes over {a,b}; show the sequence of IDs for "ababa".',
    hints: ['Compare and erase the two ends, shuttling between them, until nothing or one symbol remains.'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO5',
    part: 'c',
    source: 'Question Bank #78',
  }),
  manual({
    id: 'm5-tm-techniques',
    topic: 'tm.techniques',
    prompt: 'Briefly explain the techniques for Turing machine construction, and applications of Turing machines.',
    hints: ['Storage in the state, multiple tracks, subroutines — one sentence and one example each (§8.3).'],
    marks: 8,
    bloom: 'CL4',
    co: 'CO5',
    source: 'Question Bank #79',
  }),
  manual({
    id: 'm5-multitape',
    topic: 'tm.multitape',
    prompt: 'What is a multitape Turing machine? Prove that every language accepted by a multitape TM is recursively enumerable.',
    hints: ['Simulate k tapes on one tape with 2k tracks — head markers on the extra tracks.'],
    marks: 6,
    bloom: 'CL4',
    co: 'CO5',
    part: 'a',
    source: 'Question Bank #84',
  }),
  manual({
    id: 'm5-halt-undecidable',
    topic: 'undecidability.basics',
    prompt: 'Prove that HALT = {(M, w) : the Turing machine M halts on input w} is undecidable.',
    hints: [
      'Suppose a decider H exists; build the machine that asks H about itself and does the opposite.',
      'The contradiction is diagonalisation wearing a coat.',
    ],
    marks: 6,
    bloom: 'CL4',
    co: 'CO5',
    part: 'b',
    source: 'Question Bank #81',
  }),
  manual({
    id: 'm5-ld-not-re',
    topic: 'undecidability.basics',
    prompt: 'Prove that L_d is not recursively enumerable.',
    hints: ['If some Mᵢ accepted L_d, ask whether wᵢ ∈ L_d — either answer contradicts the diagonal.'],
    marks: 6,
    bloom: 'CL4',
    co: 'CO5',
    part: 'c',
    source: 'Question Bank #83',
  }),
  manual({
    id: 'm5-rec-vs-re',
    topic: 'undecidability.basics',
    prompt: 'If L and its complement are both recursively enumerable, show that L is recursive.',
    hints: ['Run both enumerating machines in parallel; one of them must answer.'],
    marks: 6,
    bloom: 'CL4',
    co: 'CO5',
    source: 'Question Bank #82',
  }),
]
