"""One schema, both sides — the V2 criterion. The schema is generated from
the engine's types by the bridge build; a trace from any operation must
validate against it, and it is the same trace the web app would produce,
because it is the same engine."""

import json
import pathlib

import jsonschema
import pytest

from vyakarana import DFA, ENFA

REPO = pathlib.Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO / "docs" / "trace-schema.json"


@pytest.fixture(scope="module")
def validator():
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    return jsonschema.Draft7Validator(schema)


def odd_zeros() -> DFA:
    return DFA(
        states={"a", "b"},
        alphabet={"0", "1"},
        transitions={("a", "0"): "b", ("a", "1"): "a", ("b", "0"): "a", ("b", "1"): "b"},
        start="a",
        accepting={"b"},
    )


def test_the_schema_exists_and_is_generated(validator):
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    assert "Generated by bridge/build.mjs" in schema.get("$comment", "")


def test_a_simulation_trace_validates(validator):
    trace = odd_zeros().run("0110").export_trace()
    errors = list(validator.iter_errors(trace))
    assert errors == [], [e.message for e in errors[:3]]
    assert trace["kind"] == "simulate.dfa"
    assert "counters" in trace["meta"]


def test_a_conversion_trace_validates(validator):
    n = ENFA(
        states={"q0", "q1", "q2"},
        alphabet={"a", "b"},
        transitions={("q0", None): {"q1"}, ("q1", "a"): {"q2"}},
        start="q0",
        accepting={"q2"},
    )
    d = n.to_dfa()
    trace = d.export_trace()
    errors = list(validator.iter_errors(trace))
    assert errors == [], [e.message for e in errors[:3]]
    assert trace["kind"] == "convert.nfa-to-dfa"


def test_truncation_is_visible_not_silent(validator):
    # A guard that fires must appear in meta.truncated (documentation.md §7);
    # here none fires, and the field is honestly absent rather than defaulted.
    trace = odd_zeros().run("01").export_trace()
    assert "truncated" not in trace["meta"]
