/**
 * Build the bridge into vyakarana/static/ — phases-vyakarana.md V1.
 *
 *   widget.js            the anywidget ESM bundle: viewer + renderers + React
 *   widget.css           bridge base styles + shared tokens, scoped
 *   engine-manifest.json every export the bundled engine carries, for the
 *                        V3 parity test — generated, so it cannot drift
 */

import { build } from 'esbuild'
import { createRequire } from 'node:module'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { scopeCss } from './scope-css.mjs'

const here = path.dirname(fileURLToPath(import.meta.url))
const repo = path.dirname(here)
const outDir = path.join(repo, 'vyakarana', 'vyakarana', 'static')

await mkdir(outDir, { recursive: true })

// 1. The widget bundle. React is bundled in: a notebook host provides nothing.
const widget = await build({
  entryPoints: [path.join(here, 'src', 'index.tsx')],
  bundle: true,
  format: 'esm',
  jsx: 'automatic',
  minify: true,
  define: { 'process.env.NODE_ENV': '"production"' },
  outfile: path.join(outDir, 'widget.js'),
  metafile: true,
  logLevel: 'silent',
})

// Guard the import boundary at build time as well as lint time: the bundle
// may contain packages/ui, packages/engine, react and the bridge itself.
const offenders = Object.keys(widget.metafile.inputs).filter((input) => input.includes('apps/web') || input.includes('apps\\web'))
if (offenders.length > 0) {
  throw new Error(`The bridge bundled files from apps/web, which V1 forbids:\n${offenders.join('\n')}`)
}

// 1b. The engine as an IIFE for the Python runtime's embedded V8 (ADR-004):
// the ESM widget bundle above is for browsers; mini-racer gets this one.
await build({
  entryPoints: [path.join(repo, 'packages', 'engine', 'src', 'index.ts')],
  bundle: true,
  format: 'iife',
  globalName: 'TNT',
  minify: true,
  outfile: path.join(outDir, 'engine.js'),
  logLevel: 'silent',
})

// 2. The engine manifest.
const tmp = path.join(here, '.engine-manifest-probe.cjs')
await build({
  entryPoints: [path.join(repo, 'packages', 'engine', 'src', 'index.ts')],
  bundle: true,
  format: 'cjs',
  platform: 'node',
  outfile: tmp,
  logLevel: 'silent',
})
const engine = createRequire(import.meta.url)(tmp)
await rm(tmp)
const manifest = {
  engineVersion: engine.ENGINE_VERSION,
  generated: 'by bridge/build.mjs — do not edit',
  exports: Object.keys(engine).sort(),
}
await writeFile(path.join(outDir, 'engine-manifest.json'), JSON.stringify(manifest, null, 2) + '\n')

// 3. The stylesheet: bridge base first so the shared tokens win, then scope.
const base = await readFile(path.join(here, 'src', 'styles.css'), 'utf8')
const tokens = await readFile(path.join(repo, 'packages', 'ui', 'src', 'tokens.css'), 'utf8')
const css = scopeCss(`${base}\n\n${tokens}`)
await writeFile(path.join(outDir, 'widget.css'), css)

// 4. The trace schema, generated from the engine's own types so it cannot
// drift (phases-vyakarana.md V2): docs/trace-schema.json, validated against
// by export_trace() on the Python side.
const { createGenerator } = await import('ts-json-schema-generator')
const schema = createGenerator({
  path: path.join(here, 'src', 'schema-entry.ts'),
  tsconfig: path.join(here, 'tsconfig.json'),
  type: 'TraceSchema',
  skipTypeCheck: true,
  additionalProperties: true,
}).createSchema('TraceSchema')
schema.$comment = 'Generated by bridge/build.mjs from packages/engine/src/types.ts — do not edit.'
await writeFile(path.join(repo, 'docs', 'trace-schema.json'), JSON.stringify(schema, null, 2) + '\n')

const kb = (n) => `${(n / 1024).toFixed(1)} KB`
const fs = await import('node:fs')
const sizeOf = async (name) => (await fs.promises.stat(path.join(outDir, name))).size
process.stdout.write(
  `static/: widget.js ${kb(await sizeOf('widget.js'))} · engine.js ${kb(await sizeOf('engine.js'))} · ` +
    `widget.css ${kb(css.length)} · manifest ${manifest.exports.length} exports · ` +
    `trace-schema.json ${Object.keys(schema.definitions ?? {}).length} definitions\n`,
)
